In [1]:
import numpy as np

#### Create array 'a'

In [7]:
a = np.array([[1, 6], 
              [2, 8], 
              [3, 11],
              [3, 10],
              [1, 7]])

print(a)
print("Shape of the array: {}".format(a.shape))

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]
Shape of the array: (5, 2)


#### Create array 'mean_a'

In [17]:
mean_a = np.mean(a, axis=0)
mean_a

array([2. , 8.4])

#### Create array 'a_centered'

In [18]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

#### Calculate covariance using formula

In [24]:
a_centered_column_1 = a_centered[:, 0]
a_centered_column_2 = a_centered[:, 1]
a_centered_sp = a_centered_column_1 @ a_centered_column_2
a_centered_sp

8.0

In [28]:
shape = a_centered.shape
N = shape[0]
a_covariance_by_formula = a_centered_sp / (N - 1)
a_covariance_by_formula

2.0

#### Calculate covariance using function

In [43]:
a_transposed = a.T
a_covariance_matrix = np.cov(a_transposed)
a_covariance_matrix

array([[1. , 2. ],
       [2. , 4.3]])

In [44]:
a_covariance_by_function = a_covariance_matrix[0, 1]
a_covariance_by_function

2.0